# Generated by Django 3.0.4 on 2020-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255)),
                ('tags', models.TextField(blank=True, null=True)),
                ('video_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'channel_videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('video_views', models.IntegerField(blank=True, null=True)),
                ('videos_views_median', models.IntegerField(blank=True, null=True)),
                ('perf_diff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'youtube_channels',
                'managed': False,
            },
        ),
    ]
